// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeHandlers 初始化所有Handler
func InitializeHandlers(db *gorm.DB) (*Handlers, error) {
	baseRepository := ProvideBaseRepository(db)
	userRepository := ProvideUserRepository(baseRepository)
	userService := ProvideUserService(userRepository)
	userHandler := ProvideUserHandler(userService)
	categoryRepository := ProvideCategoryRepository(baseRepository)
	categoryService := ProvideCategoryService(categoryRepository)
	categoryHandler := ProvideCategoryHandler(categoryService)
	productRepository := ProvideProductRepository(baseRepository)
	productService := ProvideProductService(productRepository, categoryRepository)
	productHandler := ProvideProductHandler(productService)
	cartRepository := ProvideCartRepository(baseRepository)
	cartService := ProvideCartService(cartRepository, productRepository)
	cartHandler := ProvideCartHandler(cartService)
	orderRepository := ProvideOrderRepository(baseRepository)
	orderService := ProvideOrderService(orderRepository, cartRepository, productRepository)
	orderHandler := ProvideOrderHandler(orderService)
	addressRepository := ProvideAddressRepository(baseRepository)
	addressService := ProvideAddressService(addressRepository)
	addressHandler := ProvideAddressHandler(addressService)
	adminHandler := ProvideAdminHandler(orderService, productService, userService)
	favoriteRepository := ProvideFavoriteRepository(baseRepository)
	favoriteService := ProvideFavoriteService(favoriteRepository, productRepository)
	favoriteHandler := ProvideFavoriteHandler(favoriteService)
	reviewRepository := ProvideReviewRepository(baseRepository)
	reviewService := ProvideReviewService(reviewRepository, orderRepository)
	reviewHandler := ProvideReviewHandler(reviewService)
	commentRepository := ProvideCommentRepository(baseRepository)
	commentService := ProvideCommentService(commentRepository, productRepository, reviewRepository)
	commentHandler := ProvideCommentHandler(commentService)
	handlers := ProvideHandlers(userHandler, categoryHandler, productHandler, cartHandler, orderHandler, addressHandler, adminHandler, favoriteHandler, reviewHandler, commentHandler)
	return handlers, nil
}

// wire.go:

// ProviderSet 所有Provider的集合
var ProviderSet = wire.NewSet(
	ProvideBaseRepository,
	ProvideUserRepository,
	ProvideCategoryRepository,
	ProvideProductRepository,
	ProvideCartRepository,
	ProvideOrderRepository,
	ProvideAddressRepository,
	ProvideFavoriteRepository,
	ProvideReviewRepository,
	ProvideCommentRepository,
	ProvideUserService,
	ProvideCategoryService,
	ProvideProductService,
	ProvideCartService,
	ProvideOrderService,
	ProvideAddressService,
	ProvideFavoriteService,
	ProvideReviewService,
	ProvideCommentService,
	ProvideUserHandler,
	ProvideCategoryHandler,
	ProvideProductHandler,
	ProvideCartHandler,
	ProvideOrderHandler,
	ProvideAddressHandler,
	ProvideAdminHandler,
	ProvideFavoriteHandler,
	ProvideReviewHandler,
	ProvideCommentHandler,
	ProvideHandlers,
)
